### PR TITLE
Full text for Legiones Astartes and Rites of War.

### PR DESCRIPTION
**Pull request by capitaladot**

### CODE REVIEW

**Comment by capitaladot** [comment]
For your consideration and review.

**Comment by Millicant** [comment]
Sweet!  Thanks man, I appreciate the work.

**Comment by Millicant** [comment]
Yeah, great updates there - lots of nice adjustments from what I can see.  Well done sir.  I'm sorry that I made issues by not uploading my work earlier.  :(  I've uploaded what I've been working on - would you mind rectifying this?  That way I can keep working!

**Comment by capitaladot** [comment]
No worries, I think I succeeded with a manual merge (XML still validated afterwards).

**Comment by capitaladot** [comment]
This issue was moved to BSData/horus-heresy#495

**Pull request closed without merging**
